// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package apptest

import (
	bytes "bytes"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

func (x *ValueField) Pick() *ValueFieldRef {
	if v := x.GetId(); len(v) > 0 {
		return ValueFieldById(v)
	}

	return nil
}

func (x *ValueField) PickUp() *ValueFieldGetRequest {
	if p := x.Pick(); p != nil {
		return ValueFieldGetRequest_builder{Ref: p}.Build()
	}
	return nil
}

func (x *ValueFieldRef) Picks(v *ValueField) bool {
	switch x.WhichKey() {
	case ValueFieldRef_Id_case:
		return x.GetId() == v.GetId()
	default:
		return false
	}
}

func (x *ValueFieldGetRequest) WithSelect(f func(s *ValueFieldSelect)) *ValueFieldGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&ValueFieldSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *ValueField) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *ValueField) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func ValueFieldById(v string) *ValueFieldRef {
	x := &ValueFieldRef{}
	x.SetId(v)
	return x
}

func ValueFieldGetById(v string) *ValueFieldGetRequest {
	return ValueFieldGetRequest_builder{Ref: ValueFieldById(v)}.Build()
}

func (x *MessageField) Pick() *MessageFieldRef {
	if v := x.GetId(); len(v) > 0 {
		return MessageFieldById(v)
	}

	return nil
}

func (x *MessageField) PickUp() *MessageFieldGetRequest {
	if p := x.Pick(); p != nil {
		return MessageFieldGetRequest_builder{Ref: p}.Build()
	}
	return nil
}

func (x *MessageFieldRef) Picks(v *MessageField) bool {
	switch x.WhichKey() {
	case MessageFieldRef_Id_case:
		return x.GetId() == v.GetId()
	default:
		return false
	}
}

func (x *MessageFieldGetRequest) WithSelect(f func(s *MessageFieldSelect)) *MessageFieldGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&MessageFieldSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *MessageField) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *MessageField) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func MessageFieldById(v string) *MessageFieldRef {
	x := &MessageFieldRef{}
	x.SetId(v)
	return x
}

func MessageFieldGetById(v string) *MessageFieldGetRequest {
	return MessageFieldGetRequest_builder{Ref: MessageFieldById(v)}.Build()
}

func (x *MapField) Pick() *MapFieldRef {
	if v := x.GetId(); len(v) > 0 {
		return MapFieldById(v)
	}

	return nil
}

func (x *MapField) PickUp() *MapFieldGetRequest {
	if p := x.Pick(); p != nil {
		return MapFieldGetRequest_builder{Ref: p}.Build()
	}
	return nil
}

func (x *MapFieldRef) Picks(v *MapField) bool {
	switch x.WhichKey() {
	case MapFieldRef_Id_case:
		return x.GetId() == v.GetId()
	default:
		return false
	}
}

func (x *MapFieldGetRequest) WithSelect(f func(s *MapFieldSelect)) *MapFieldGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&MapFieldSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *MapField) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *MapField) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func MapFieldById(v string) *MapFieldRef {
	x := &MapFieldRef{}
	x.SetId(v)
	return x
}

func MapFieldGetById(v string) *MapFieldGetRequest {
	return MapFieldGetRequest_builder{Ref: MapFieldById(v)}.Build()
}

func (x *Tenant) Pick() *TenantRef {
	if v := x.GetId(); len(v) > 0 {
		return TenantById(v)
	}

	return nil
}

func (x *Tenant) PickUp() *TenantGetRequest {
	if p := x.Pick(); p != nil {
		return TenantGetRequest_builder{Ref: p}.Build()
	}
	return nil
}

func (x *TenantRef) Picks(v *Tenant) bool {
	switch x.WhichKey() {
	case TenantRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func (x *TenantGetRequest) WithSelect(f func(s *TenantSelect)) *TenantGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&TenantSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *Tenant) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *Tenant) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func TenantById(v []byte) *TenantRef {
	x := &TenantRef{}
	x.SetId(v)
	return x
}

func TenantGetById(v []byte) *TenantGetRequest {
	return TenantGetRequest_builder{Ref: TenantById(v)}.Build()
}

func (x *User) Pick() *UserRef {
	if v := x.GetId(); len(v) > 0 {
		return UserById(v)
	}
	{
		v1 := x.GetAlias()
		v2 := x.GetTenant()
		if len(v1) > 0 && v2 != nil {
			return UserByAlias(v1, v2.Pick())
		}
	}

	return nil
}

func (x *User) PickUp() *UserGetRequest {
	if p := x.Pick(); p != nil {
		return UserGetRequest_builder{Ref: p}.Build()
	}
	return nil
}

func (x *UserRef) Picks(v *User) bool {
	switch x.WhichKey() {
	case UserRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	case UserRef_Alias_case:
		x := x.GetAlias()
		return (x.GetAlias() == v.GetAlias()) &&
			(x.GetTenant().Picks(v.GetTenant()))
	default:
		return false
	}
}

func (x *UserGetRequest) WithSelect(f func(s *UserSelect)) *UserGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&UserSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *User) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *User) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func UserById(v []byte) *UserRef {
	x := &UserRef{}
	x.SetId(v)
	return x
}

func UserGetById(v []byte) *UserGetRequest {
	return UserGetRequest_builder{Ref: UserById(v)}.Build()
}

func UserByAlias(alias string, tenant *TenantRef) *UserRef {
	x := &UserRefByAlias{}
	x.SetAlias(alias)
	x.SetTenant(tenant)
	return UserRef_builder{Alias: x}.Build()
}

func UserGetByAlias(alias string, tenant *TenantRef) *UserGetRequest {
	return UserGetRequest_builder{Ref: UserByAlias(alias, tenant)}.Build()
}
