// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package apptest

import (
	bytes "bytes"
)

func (x *ValueField) Pick() *ValueFieldRef {
	return ValueFieldById(x.GetId())
}

func (x *ValueFieldRef) Picks(v *ValueField) bool {
	switch x.WhichKey() {
	case ValueFieldRef_Id_case:
		return x.GetId() == v.GetId()
	default:
		return false
	}
}

func ValueFieldById(v string) *ValueFieldRef {
	x := &ValueFieldRef{}
	x.SetId(v)
	return x
}

func (x *MessageField) Pick() *MessageFieldRef {
	return MessageFieldById(x.GetId())
}

func (x *MessageFieldRef) Picks(v *MessageField) bool {
	switch x.WhichKey() {
	case MessageFieldRef_Id_case:
		return x.GetId() == v.GetId()
	default:
		return false
	}
}

func MessageFieldById(v string) *MessageFieldRef {
	x := &MessageFieldRef{}
	x.SetId(v)
	return x
}

func (x *MapField) Pick() *MapFieldRef {
	return MapFieldById(x.GetId())
}

func (x *MapFieldRef) Picks(v *MapField) bool {
	switch x.WhichKey() {
	case MapFieldRef_Id_case:
		return x.GetId() == v.GetId()
	default:
		return false
	}
}

func MapFieldById(v string) *MapFieldRef {
	x := &MapFieldRef{}
	x.SetId(v)
	return x
}

func (x *Tenant) Pick() *TenantRef {
	return TenantById(x.GetId())
}

func (x *TenantRef) Picks(v *Tenant) bool {
	switch x.WhichKey() {
	case TenantRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func TenantById(v []byte) *TenantRef {
	x := &TenantRef{}
	x.SetId(v)
	return x
}

func (x *User) Pick() *UserRef {
	return UserById(x.GetId())
}

func (x *UserRef) Picks(v *User) bool {
	switch x.WhichKey() {
	case UserRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	case UserRef_Alias_case:
		x := x.GetAlias()
		return (x.GetAlias() == v.GetAlias()) &&
			(x.GetTenant().Picks(v.GetTenant()))
	default:
		return false
	}
}

func UserByAlias(alias string, tenant *TenantRef) *UserRefByAlias {
	x := &UserRefByAlias{}
	x.SetAlias(alias)
	x.SetTenant(tenant)
	return x
}

func UserById(v []byte) *UserRef {
	x := &UserRef{}
	x.SetId(v)
	return x
}
