// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package apptest

import (
	grpc "google.golang.org/grpc"
)

type Server interface {
	ValueField() ValueFieldServiceServer
	MessageField() MessageFieldServiceServer
	MapField() MapFieldServiceServer
	Tenant() TenantServiceServer
	User() UserServiceServer
}

func RegisterServer(g *grpc.Server, s Server) {
	RegisterValueFieldServiceServer(g, s.ValueField())
	RegisterMessageFieldServiceServer(g, s.MessageField())
	RegisterMapFieldServiceServer(g, s.MapField())
	RegisterTenantServiceServer(g, s.Tenant())
	RegisterUserServiceServer(g, s.User())
}

type StaticServer struct {
	ValueFieldServer   ValueFieldServiceServer
	MessageFieldServer MessageFieldServiceServer
	MapFieldServer     MapFieldServiceServer
	TenantServer       TenantServiceServer
	UserServer         UserServiceServer
}

func (s *StaticServer) ValueField() ValueFieldServiceServer     { return s.ValueFieldServer }
func (s *StaticServer) MessageField() MessageFieldServiceServer { return s.MessageFieldServer }
func (s *StaticServer) MapField() MapFieldServiceServer         { return s.MapFieldServer }
func (s *StaticServer) Tenant() TenantServiceServer             { return s.TenantServer }
func (s *StaticServer) User() UserServiceServer                 { return s.UserServer }

type Client interface {
	ValueField() ValueFieldServiceClient
	MessageField() MessageFieldServiceClient
	MapField() MapFieldServiceClient
	Tenant() TenantServiceClient
	User() UserServiceClient
}

func NewClient(c *grpc.ClientConn) Client {
	return &client{
		_ValueField:   NewValueFieldServiceClient(c),
		_MessageField: NewMessageFieldServiceClient(c),
		_MapField:     NewMapFieldServiceClient(c),
		_Tenant:       NewTenantServiceClient(c),
		_User:         NewUserServiceClient(c),
	}
}

type client struct {
	_ValueField   ValueFieldServiceClient
	_MessageField MessageFieldServiceClient
	_MapField     MapFieldServiceClient
	_Tenant       TenantServiceClient
	_User         UserServiceClient
}

func (c *client) ValueField() ValueFieldServiceClient     { return c._ValueField }
func (c *client) MessageField() MessageFieldServiceClient { return c._MessageField }
func (c *client) MapField() MapFieldServiceClient         { return c._MapField }
func (c *client) Tenant() TenantServiceClient             { return c._Tenant }
func (c *client) User() UserServiceClient                 { return c._User }
