// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/field.proto

package ent

import (
	apptest "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest"
)

func (e *ValueField) Proto() *apptest.ValueField {
	x := &apptest.ValueField{}
	x.SetId(e.ID)
	x.SetImplicitF64(e.ImplicitF64)
	x.SetImplicitF32(e.ImplicitF32)
	x.SetImplicitI32(e.ImplicitI32)
	x.SetImplicitI64(e.ImplicitI64)
	x.SetImplicitU32(e.ImplicitU32)
	x.SetImplicitU64(e.ImplicitU64)
	x.SetImplicitSi32(e.ImplicitSi32)
	x.SetImplicitSi64(e.ImplicitSi64)
	x.SetImplicitFi32(e.ImplicitFi32)
	x.SetImplicitFi64(e.ImplicitFi64)
	x.SetImplicitSfi32(e.ImplicitSfi32)
	x.SetImplicitSfi64(e.ImplicitSfi64)
	x.SetImplicitBool(e.ImplicitBool)
	x.SetImplicitString(e.ImplicitString)
	x.SetImplicitBytes(e.ImplicitBytes)
	x.SetImplicitEnum(apptest.Level(e.ImplicitEnum))
	if e.ExplicitF64 != nil {
		x.SetExplicitF64(*e.ExplicitF64)
	}
	if e.ExplicitF32 != nil {
		x.SetExplicitF32(*e.ExplicitF32)
	}
	if e.ExplicitI32 != nil {
		x.SetExplicitI32(*e.ExplicitI32)
	}
	if e.ExplicitI64 != nil {
		x.SetExplicitI64(*e.ExplicitI64)
	}
	if e.ExplicitU32 != nil {
		x.SetExplicitU32(*e.ExplicitU32)
	}
	if e.ExplicitU64 != nil {
		x.SetExplicitU64(*e.ExplicitU64)
	}
	if e.ExplicitSi32 != nil {
		x.SetExplicitSi32(*e.ExplicitSi32)
	}
	if e.ExplicitSi64 != nil {
		x.SetExplicitSi64(*e.ExplicitSi64)
	}
	if e.ExplicitFi32 != nil {
		x.SetExplicitFi32(*e.ExplicitFi32)
	}
	if e.ExplicitFi64 != nil {
		x.SetExplicitFi64(*e.ExplicitFi64)
	}
	if e.ExplicitSfi32 != nil {
		x.SetExplicitSfi32(*e.ExplicitSfi32)
	}
	if e.ExplicitSfi64 != nil {
		x.SetExplicitSfi64(*e.ExplicitSfi64)
	}
	if e.ExplicitBool != nil {
		x.SetExplicitBool(*e.ExplicitBool)
	}
	if e.ExplicitString != nil {
		x.SetExplicitString(*e.ExplicitString)
	}
	if e.ExplicitBytes != nil {
		x.SetExplicitBytes(*e.ExplicitBytes)
	}
	if e.ExplicitEnum != nil {
		x.SetExplicitEnum(apptest.Level(*e.ExplicitEnum))
	}
	x.SetImplicitF64S(e.ImplicitF64s)
	x.SetImplicitF32S(e.ImplicitF32s)
	x.SetImplicitI32S(e.ImplicitI32s)
	x.SetImplicitI64S(e.ImplicitI64s)
	x.SetImplicitU32S(e.ImplicitU32s)
	x.SetImplicitU64S(e.ImplicitU64s)
	x.SetImplicitSi32S(e.ImplicitSi32s)
	x.SetImplicitSi64S(e.ImplicitSi64s)
	x.SetImplicitFi32S(e.ImplicitFi32s)
	x.SetImplicitFi64S(e.ImplicitFi64s)
	x.SetImplicitSfi32S(e.ImplicitSfi32s)
	x.SetImplicitSfi64S(e.ImplicitSfi64s)
	x.SetImplicitBools(e.ImplicitBools)
	x.SetImplicitStrings(e.ImplicitStrings)
	x.SetImplicitBytess(e.ImplicitBytess)
	x.SetImplicitLevels(e.ImplicitLevels)
	if e.NullableF64 != nil {
		x.SetNullableF64(*e.NullableF64)
	}
	if e.NullableF32 != nil {
		x.SetNullableF32(*e.NullableF32)
	}
	if e.NullableI32 != nil {
		x.SetNullableI32(*e.NullableI32)
	}
	if e.NullableI64 != nil {
		x.SetNullableI64(*e.NullableI64)
	}
	if e.NullableU32 != nil {
		x.SetNullableU32(*e.NullableU32)
	}
	if e.NullableU64 != nil {
		x.SetNullableU64(*e.NullableU64)
	}
	if e.NullableSi32 != nil {
		x.SetNullableSi32(*e.NullableSi32)
	}
	if e.NullableSi64 != nil {
		x.SetNullableSi64(*e.NullableSi64)
	}
	if e.NullableFi32 != nil {
		x.SetNullableFi32(*e.NullableFi32)
	}
	if e.NullableFi64 != nil {
		x.SetNullableFi64(*e.NullableFi64)
	}
	if e.NullableSfi32 != nil {
		x.SetNullableSfi32(*e.NullableSfi32)
	}
	if e.NullableSfi64 != nil {
		x.SetNullableSfi64(*e.NullableSfi64)
	}
	if e.NullableBool != nil {
		x.SetNullableBool(*e.NullableBool)
	}
	if e.NullableString != nil {
		x.SetNullableString(*e.NullableString)
	}
	if e.NullableBytes != nil {
		x.SetNullableBytes(*e.NullableBytes)
	}
	if e.NullableLevel != nil {
		x.SetNullableLevel(apptest.Level(*e.NullableLevel))
	}
	x.SetImplicitF64WithDefault(e.ImplicitF64WithDefault)
	x.SetImplicitF32WithDefault(e.ImplicitF32WithDefault)
	x.SetImplicitI32WithDefault(e.ImplicitI32WithDefault)
	x.SetImplicitI64WithDefault(e.ImplicitI64WithDefault)
	x.SetImplicitU32WithDefault(e.ImplicitU32WithDefault)
	x.SetImplicitU64WithDefault(e.ImplicitU64WithDefault)
	x.SetImplicitSi32WithDefault(e.ImplicitSi32WithDefault)
	x.SetImplicitSi64WithDefault(e.ImplicitSi64WithDefault)
	x.SetImplicitFi32WithDefault(e.ImplicitFi32WithDefault)
	x.SetImplicitFi64WithDefault(e.ImplicitFi64WithDefault)
	x.SetImplicitSfi32WithDefault(e.ImplicitSfi32WithDefault)
	x.SetImplicitSfi64WithDefault(e.ImplicitSfi64WithDefault)
	x.SetImplicitBoolWithDefault(e.ImplicitBoolWithDefault)
	x.SetImplicitStringWithDefault(e.ImplicitStringWithDefault)
	x.SetImplicitBytesWithDefault(e.ImplicitBytesWithDefault)
	x.SetImplicitLevelWithDefault(apptest.Level(e.ImplicitLevelWithDefault))
	if e.ExplicitF64WithDefault != nil {
		x.SetExplicitF64WithDefault(*e.ExplicitF64WithDefault)
	}
	if e.ExplicitF32WithDefault != nil {
		x.SetExplicitF32WithDefault(*e.ExplicitF32WithDefault)
	}
	if e.ExplicitI32WithDefault != nil {
		x.SetExplicitI32WithDefault(*e.ExplicitI32WithDefault)
	}
	if e.ExplicitI64WithDefault != nil {
		x.SetExplicitI64WithDefault(*e.ExplicitI64WithDefault)
	}
	if e.ExplicitU32WithDefault != nil {
		x.SetExplicitU32WithDefault(*e.ExplicitU32WithDefault)
	}
	if e.ExplicitU64WithDefault != nil {
		x.SetExplicitU64WithDefault(*e.ExplicitU64WithDefault)
	}
	if e.ExplicitSi32WithDefault != nil {
		x.SetExplicitSi32WithDefault(*e.ExplicitSi32WithDefault)
	}
	if e.ExplicitSi64WithDefault != nil {
		x.SetExplicitSi64WithDefault(*e.ExplicitSi64WithDefault)
	}
	if e.ExplicitFi32WithDefault != nil {
		x.SetExplicitFi32WithDefault(*e.ExplicitFi32WithDefault)
	}
	if e.ExplicitFi64WithDefault != nil {
		x.SetExplicitFi64WithDefault(*e.ExplicitFi64WithDefault)
	}
	if e.ExplicitSfi32WithDefault != nil {
		x.SetExplicitSfi32WithDefault(*e.ExplicitSfi32WithDefault)
	}
	if e.ExplicitSfi64WithDefault != nil {
		x.SetExplicitSfi64WithDefault(*e.ExplicitSfi64WithDefault)
	}
	if e.ExplicitBoolWithDefault != nil {
		x.SetExplicitBoolWithDefault(*e.ExplicitBoolWithDefault)
	}
	if e.ExplicitStringWithDefault != nil {
		x.SetExplicitStringWithDefault(*e.ExplicitStringWithDefault)
	}
	if e.ExplicitBytesWithDefault != nil {
		x.SetExplicitBytesWithDefault(*e.ExplicitBytesWithDefault)
	}
	if e.ExplicitLevelWithDefault != nil {
		x.SetExplicitLevelWithDefault(apptest.Level(*e.ExplicitLevelWithDefault))
	}
	x.SetImplicitImmutableF64(e.ImplicitImmutableF64)
	x.SetImplicitImmutableF32(e.ImplicitImmutableF32)
	x.SetImplicitImmutableI32(e.ImplicitImmutableI32)
	x.SetImplicitImmutableI64(e.ImplicitImmutableI64)
	x.SetImplicitImmutableU32(e.ImplicitImmutableU32)
	x.SetImplicitImmutableU64(e.ImplicitImmutableU64)
	x.SetImplicitImmutableSi32(e.ImplicitImmutableSi32)
	x.SetImplicitImmutableSi64(e.ImplicitImmutableSi64)
	x.SetImplicitImmutableFi32(e.ImplicitImmutableFi32)
	x.SetImplicitImmutableFi64(e.ImplicitImmutableFi64)
	x.SetImplicitImmutableSfi32(e.ImplicitImmutableSfi32)
	x.SetImplicitImmutableSfi64(e.ImplicitImmutableSfi64)
	x.SetImplicitImmutableBool(e.ImplicitImmutableBool)
	x.SetImplicitImmutableString(e.ImplicitImmutableString)
	x.SetImplicitImmutableBytes(e.ImplicitImmutableBytes)
	x.SetImplicitImmutableLevel(apptest.Level(e.ImplicitImmutableLevel))
	if e.ExplicitImmutableF64 != nil {
		x.SetExplicitImmutableF64(*e.ExplicitImmutableF64)
	}
	if e.ExplicitImmutableF32 != nil {
		x.SetExplicitImmutableF32(*e.ExplicitImmutableF32)
	}
	if e.ExplicitImmutableI32 != nil {
		x.SetExplicitImmutableI32(*e.ExplicitImmutableI32)
	}
	if e.ExplicitImmutableI64 != nil {
		x.SetExplicitImmutableI64(*e.ExplicitImmutableI64)
	}
	if e.ExplicitImmutableU32 != nil {
		x.SetExplicitImmutableU32(*e.ExplicitImmutableU32)
	}
	if e.ExplicitImmutableU64 != nil {
		x.SetExplicitImmutableU64(*e.ExplicitImmutableU64)
	}
	if e.ExplicitImmutableSi32 != nil {
		x.SetExplicitImmutableSi32(*e.ExplicitImmutableSi32)
	}
	if e.ExplicitImmutableSi64 != nil {
		x.SetExplicitImmutableSi64(*e.ExplicitImmutableSi64)
	}
	if e.ExplicitImmutableFi32 != nil {
		x.SetExplicitImmutableFi32(*e.ExplicitImmutableFi32)
	}
	if e.ExplicitImmutableFi64 != nil {
		x.SetExplicitImmutableFi64(*e.ExplicitImmutableFi64)
	}
	if e.ExplicitImmutableSfi32 != nil {
		x.SetExplicitImmutableSfi32(*e.ExplicitImmutableSfi32)
	}
	if e.ExplicitImmutableSfi64 != nil {
		x.SetExplicitImmutableSfi64(*e.ExplicitImmutableSfi64)
	}
	if e.ExplicitImmutableBool != nil {
		x.SetExplicitImmutableBool(*e.ExplicitImmutableBool)
	}
	if e.ExplicitImmutableString != nil {
		x.SetExplicitImmutableString(*e.ExplicitImmutableString)
	}
	if e.ExplicitImmutableBytes != nil {
		x.SetExplicitImmutableBytes(*e.ExplicitImmutableBytes)
	}
	if e.ExplicitImmutableLevel != nil {
		x.SetExplicitImmutableLevel(apptest.Level(*e.ExplicitImmutableLevel))
	}
	return x
}
func (e *MessageField) Proto() *apptest.MessageField {
	x := &apptest.MessageField{}
	x.SetId(e.ID)
	if e.Explicit != nil {
		x.SetExplicit(e.Explicit)
	}
	x.SetRepeated(e.Repeated)
	if e.Nullable != nil {
		x.SetNullable(e.Nullable)
	}
	if e.ExplicitWithDefault != nil {
		x.SetExplicitWithDefault(e.ExplicitWithDefault)
	}
	if e.ExplicitImmutable != nil {
		x.SetExplicitImmutable(e.ExplicitImmutable)
	}
	return x
}
func (e *MapField) Proto() *apptest.MapField {
	x := &apptest.MapField{}
	x.SetId(e.ID)
	x.SetImplicitString(e.ImplicitString)
	x.SetImplicitEnum(e.ImplicitEnum)
	x.SetImplicitJson(e.ImplicitJSON)
	x.SetImplicitStringWithDefault(e.ImplicitStringWithDefault)
	x.SetImplicitEnumWithDefault(e.ImplicitEnumWithDefault)
	x.SetImplicitJsonWithDefault(e.ImplicitJSONWithDefault)
	x.SetImplicitImmutableString(e.ImplicitImmutableString)
	x.SetImplicitImmutableEnum(e.ImplicitImmutableEnum)
	x.SetImplicitImmutableJson(e.ImplicitImmutableJSON)
	return x
}
