// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/note.proto

package ent

import (
	apptest "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Note) Proto() *apptest.Note {
	x := &apptest.Note{}
	x.SetId(e.Id[:])
	x.SetAlias(e.Alias)
	x.SetBody(e.Body)
	x.SetSlug(e.Slug)
	if e.DateErased != nil {
		x.SetDateErased(timestamppb.New(*e.DateErased))
	}
	x.SetDateUpdated(timestamppb.New(e.DateUpdated))
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
