// Code generated by protoc-gen-orm-ent. DO NOT EDIT.

package ent

import (
	dialect "entgo.io/ent/dialect"
)

// Dialect is the SQL this client speaks.
//
// A server that writes SQL of its own has to know which SQL it may write,
// and the connection is what settles that. Asking the client rather than
// the caller is what keeps the answer from being a second, separate claim
// that can disagree with the first.
func (c *Client) Dialect() string {
	return c.driver.Dialect()
}

// Driver is what this client runs its queries through.
//
// It is what a transaction is begun on when several clients are to share
// one; see the enttx package and [Client.WithDriver].
func (c *Client) Driver() dialect.Driver {
	return c.driver
}

// WithDriver answers with a client that runs through drv and is this one in
// every other way.
//
// The hooks, the interceptors and the debug setting come along, which is the
// point: building a fresh client from the driver reaches the same database
// and quietly drops all three. This is what [Client.Tx] does to bind a
// client to a transaction, spelled for a driver that came from elsewhere.
func (c *Client) WithDriver(drv dialect.Driver) *Client {
	cfg := c.config
	cfg.driver = drv
	client := &Client{config: cfg}
	client.init()
	return client
}

// InTx reports whether this client is already bound to a transaction of
// Ent's own, which is the one [Client.Tx] refuses to nest.
//
// It is the same question Tx asks itself, so a caller can ask it first
// instead of starting a transaction to find out. A driver from enttx is
// not one of these and does not answer true: it hands out transactions
// that cannot end the one it holds, so nesting on it is already safe.
func (c *Client) InTx() bool {
	_, ok := c.driver.(*txDriver)
	return ok
}
