// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/seat.proto

package ent

import (
	apptest "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest"
	uuid "uuid"
)

func (e *Seat) Proto() *apptest.Seat {
	x := &apptest.Seat{}
	x.SetId(e.Id[:])
	if v := e.Edges.Holder; v != nil {
		x.SetHolder(v.Proto())
	} else if v := e.HolderId; v != *new(uuid.UUID) {
		r := &apptest.User{}
		r.SetId(v[:])
		x.SetHolder(r)
	}
	if v := e.Edges.Org; v != nil {
		x.SetOrg(v.Proto())
	} else if v := e.OrgId; v != *new(uuid.UUID) {
		r := &apptest.Tenant{}
		r.SetId(v[:])
		x.SetOrg(r)
	}
	if v := e.Edges.Deputy; v != nil {
		x.SetDeputy(v.Proto())
	} else if v := e.DeputyId; v != *new(uuid.UUID) {
		r := &apptest.User{}
		r.SetId(v[:])
		x.SetDeputy(r)
	}
	return x
}
