// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/shift.proto

package ent

import (
	apptest "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Shift) Proto() *apptest.Shift {
	x := &apptest.Shift{}
	x.SetId(e.Id[:])
	x.SetDesk(e.Desk)
	x.SetStartsAt(timestamppb.New(e.StartsAt))
	return x
}
