// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/tenant.proto

package ent

import (
	apptest "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Tenant) Proto() *apptest.Tenant {
	x := &apptest.Tenant{}
	x.SetId(e.ID[:])
	x.SetAlias(e.Alias)
	x.SetName(e.Name)
	x.SetLabels(e.Labels)
	if e.DateCreated != nil {
		x.SetDateCreated(timestamppb.New(*e.DateCreated))
	}
	return x
}
