// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/user.proto

package ent

import (
	apptest "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	uuid "uuid"
)

func (e *User) Proto() *apptest.User {
	x := &apptest.User{}
	x.SetId(e.Id[:])
	if v := e.Edges.Tenant; v != nil {
		x.SetTenant(v.Proto())
	} else if v := e.TenantId; v != *new(uuid.UUID) {
		r := &apptest.Tenant{}
		r.SetId(v[:])
		x.SetTenant(r)
	}
	x.SetAlias(e.Alias)
	x.SetName(e.Name)
	x.SetLabels(e.Labels)
	if e.Lock != nil {
		x.SetLock(*e.Lock)
	}
	x.SetDateUpdated(timestamppb.New(e.DateUpdated))
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
