// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/user.proto

package ent

import (
	apptest "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *User) Proto() *apptest.User {
	x := &apptest.User{}
	x.SetId(e.ID[:])
	if v := e.Edges.Tenant; v != nil {
		x.SetTenant(v.Proto())
	}
	x.SetAlias(e.Alias)
	x.SetName(e.Name)
	x.SetLabels(e.Labels)
	if e.Lock != nil {
		x.SetLock(*e.Lock)
	}
	if e.DateCreated != nil {
		x.SetDateCreated(timestamppb.New(*e.DateCreated))
	}
	return x
}
