package app

import (
	"context"
	"github.com/protobuf-orm/protoc-gen-orm-ent/internal/work"

	"github.com/protobuf-orm/protobuf-orm/graph"
	"google.golang.org/protobuf/compiler/protogen"
)

type App struct {
	name string

	ent protogen.GoImportPath
}

func New(ent protogen.GoImportPath, opts ...Option) (*App, error) {
	a := &App{
		ent: ent,
	}
	for _, opt := range opts {
		opt(a)
	}
	if a.name == "" {
		a.name = "server/bare/store.g.go"
	}

	return a, nil
}

func (a *App) Run(ctx context.Context, p *protogen.Plugin, g *graph.Graph) error {
	gf, f := a.newGeneratedFile(p, g)
	if gf == nil {
		// No entity found.
		return nil
	}

	vs := make([]graph.Entity, 0, len(g.Entities))
	for _, f := range p.Files {
		for _, m := range f.Messages {
			v, ok := g.Entities[m.Desc.FullName()]
			if !ok {
				continue
			}

			vs = append(vs, v)
		}
	}

	w := &Work{
		GeneratedFile: gf,

		Entities: vs,
		Package:  f.GoImportPath,
		Ent:      work.At(f.GoImportPath, string(a.ent)),
	}

	w.xServer()

	return nil
}

func (a *App) newGeneratedFile(p *protogen.Plugin, g *graph.Graph) (*protogen.GeneratedFile, *protogen.File) {
	var f *protogen.File
L:
	for _, f_ := range p.Files {
		for _, m := range f_.Messages {
			if _, ok := g.Entities[m.Desc.FullName()]; !ok {
				continue
			}

			f = f_
			break L
		}
	}
	if f == nil {
		return nil, nil
	}

	dir, _ := work.Split(f.GeneratedFilenamePrefix)
	path := string(work.At(protogen.GoImportPath(dir), a.name))

	pkg := work.Dir(path)

	gf := p.NewGeneratedFile(path, pkg)
	gf.P(`// Code generated by protoc-gen-orm-ent. DO NOT EDIT.`)
	gf.P("")
	gf.P("package " + work.Base(pkg))
	gf.P("")

	return gf, f
}
