package app

import "github.com/protobuf-orm/protoc-gen-orm-ent/internal/work"

// xRecorder emits what a server says about a write it made, and to whom.
//
// It is the one place every write arrives at. Add, Patch, Apply and Erase are
// four RPCs and three code paths, and an app that has to know what changed --
// to keep an audit trail, to invalidate a cache, to publish an event -- would
// otherwise reimplement all of them in a layer in front, once per entity, and
// go on doing so for every entity added afterwards. Patch is the sharpest case:
// it is not an RPC that a layer in front can watch Apply for, because it
// converts its request into a document and joins Apply's path *inside* this
// server, below anything that could have been stacked on top.
//
// It is told inside the transaction that makes the write, so what it does and
// what it was told about hold or fall together, and it is told after the write
// rather than before: a recorder is for what happened, and a rule about what
// may happen belongs in a server in front of this one.
func (w *Work) xRecorder() {
	w.P("// Change is one write: what was asked for, and what this server did about")
	w.P("// it.")
	w.P("type Change struct {")
	w.P("	// Method is what the caller asked for -- the RPC gRPC dispatched, by")
	w.P("	// the name it knows it by, such as \"/pkg.HolderService/Rename\".")
	w.P("	//")
	w.P("	// It is the whole request's and not this leg of it, which is the")
	w.P("	// difference that makes it worth carrying. One call writes through")
	w.P("	// several of these servers -- adding a Tenant writes the admin Holder")
	w.P("	// that comes with it -- and an RPC written by hand ends in an Apply that")
	w.P("	// nobody called by that name. A trail that said [Change.By] here would")
	w.P("	// answer \"who renamed this\" with a method the caller has never heard")
	w.P("	// of.")
	w.P("	//")
	w.P("	// A write nobody called over the wire has no such thing, and then this")
	w.P("	// is [Change.By]. That is the honest answer rather than a fallback: the")
	w.P("	// deployment writing to itself at startup did call it, in the only sense")
	w.P("	// in which anything called it.")
	w.P("	Method string")
	w.P("")
	w.P("	// By is the RPC of *this* server that made the write, which is what")
	w.P("	// actually happened to the row.")
	w.P("	//")
	w.P("	// It says which entity and which kind of write without a field for")
	w.P("	// either: a service is named for the entity it is about, and it is")
	w.P("	// always one of the four this server has -- an Add adds and an Erase")
	w.P("	// erases, and Patch and Apply are one write by two roads.")
	w.P("	//")
	w.P("	// So the two answer different questions and a recorder wants the one it")
	w.P("	// is for. A trail is read by somebody asking what was asked for, and")
	w.P("	// takes Method. Anything that acts on the row itself -- a cache to drop,")
	w.P("	// an event to publish -- has to know which row and which write, and")
	w.P("	// takes this.")
	w.P("	By string")
	w.P("")
	w.P("	// Key is the row, as Go holds the key of this entity: a uuid.UUID, a")
	w.P("	// string, whatever the schema declared. It is the key and never the")
	w.P("	// reference the request named the row by, which may have been an alias,")
	w.P("	// and may not name the same row a moment later.")
	w.P("	Key any")
	w.P("")
	w.P("	// Patch is the document the write was compiled from, and nil for a")
	w.P("	// write that was not one. A Patch request converts into a document, so")
	w.P("	// both RPCs arrive with the same thing to say and a recorder does not")
	w.P("	// have to know which one it was -- [Change.By] still says.")
	w.P("	//")
	w.P("	// It is what was asked for and not a redo log. What the server settled")
	w.P("	// on itself is not in it: the version stamp of an Apply, and the key and")
	w.P("	// the timestamps an Add makes up for a request that left them out.")
	w.P("	Patch *", work.PkgPatchPb.Ident("Patch"))
	w.P("}")
	w.P("")

	w.P("// Recorder is told about every write, inside the transaction that makes")
	w.P("// it and before it is committed.")
	w.P("//")
	w.P("// Write through the server it is handed and through nothing else. That")
	w.P("// server runs on the write's own transaction, so what it does is part of")
	w.P("// that write, and it does not record -- a recorder that recorded its own")
	w.P("// writes would not stop. Another client is another connection, and on a")
	w.P("// pool of one it waits for the connection this transaction is holding,")
	w.P("// which is a hang rather than an error.")
	w.P("//")
	w.P("// An error it answers with is reported to the caller, and the write is")
	w.P("// undone with it *when this server opened the transaction*. When it")
	w.P("// joined one that a caller began -- see enttx -- undoing it is not this")
	w.P("// server's to do: the refusal is reported, and whoever began the")
	w.P("// transaction says whether the whole of it still holds. A caller that")
	w.P("// carries on past a failed call commits a write that nothing recorded.")
	w.P("//")
	w.P("// The guarantee is about the database and nothing else. Anything a")
	w.P("// recorder does elsewhere -- a message published, a cache dropped --")
	w.P("// outlives a rollback, so what has to hold with the write has to be")
	w.P("// written with it, as a row somebody else picks up.")
	w.P("//")
	w.P("// The server it is handed carries no scope either, so a recorder sees")
	w.P("// every row rather than the ones the request was allowed to. That is")
	w.P("// what it is for: a trail that could not read what it just wrote about,")
	w.P("// or that recorded only the writes the caller could see, would be a")
	w.P("// trail of the wrong thing. See [Scopes].")
	w.P("type Recorder interface {")
	w.P("	Record(ctx ", work.IdentContext, ", s Server, c Change) error")
	w.P("}")
	w.P("")

	w.P("// Recorders is told about a write in the order they are written, and")
	w.P("// stops at the first one that refuses. [WithRecorder] builds one of these")
	w.P("// as soon as it is given a second recorder.")
	w.P("//")
	w.P("// Every one of them is *required*: the write is undone for any of them.")
	w.P("// That is the right default, since a trail is what this exists for and a")
	w.P("// row written while nothing recorded it is the failure nobody notices.")
	w.P("// It is not right for all of them -- a cache that was not dropped and a")
	w.P("// message that was not published are worth a log line rather than a")
	w.P("// refused write -- and a recorder that means that says so by answering")
	w.P("// nil and dealing with its own errors. There is no option here that means")
	w.P("// it, because the choice belongs to whoever wrote the recorder and not to")
	w.P("// whoever assembled the server.")
	w.P("type Recorders []Recorder")
	w.P("")
	w.P("func (rs Recorders) Record(ctx ", work.IdentContext, ", s Server, c Change) error {")
	w.P("	for _, r := range rs {")
	w.P("		if err := r.Record(ctx, s, c); err != nil {")
	w.P("			return err")
	w.P("		}")
	w.P("	}")
	w.P("	return nil")
	w.P("}")
	w.P("")

	w.P("// record tells `rec` about `c`, and is what the servers call so that a")
	w.P("// nil recorder costs a comparison rather than a branch at every site.")
	w.P("//")
	w.P("// What a recorder answers with is reported as Internal, whatever it was.")
	w.P("// A recorder writes through a server of its own and that server answers")
	w.P("// in the same words this one does -- an AlreadyExists about the row the")
	w.P("// *trail* collided on would reach the caller as an AlreadyExists about")
	w.P("// the row it was writing, and a caller that acts on that code, as one")
	w.P("// looking for an entity that is already there does, would act on a")
	w.P("// conflict that was never its own. Keeping the trail is this server's")
	w.P("// job, so failing to is this server's fault.")
	w.P("//")
	w.P("// It is also where [Change.Method] is filled in. The write sites know")
	w.P("// which RPC of this server they are, and the request knows what it was")
	w.P("// asked for; asking gRPC once here is what keeps the two from being")
	w.P("// spelled out at every one of them.")
	w.P("func record(ctx ", work.IdentContext, ", rec Recorder, db *", w.Ent.Ident("Client"), ", c Change) error {")
	w.P("	if rec == nil {")
	w.P("		return nil")
	w.P("	}")
	w.P("	if v, ok := ", work.PkgGrpc.Ident("Method"), "(ctx); ok {")
	w.P("		c.Method = v")
	w.P("	} else {")
	w.P("		c.Method = c.By")
	w.P("	}")
	w.P("	if err := rec.Record(ctx, Server{Store: Store{Db: db}}, c); err != nil {")
	w.P("		return ", work.PkgGrpcStatus.Ident("Errorf"), "(", work.PkgGrpcCodes.Ident("Internal"),
		", \"record the write by %s: %s\", c.By, err)")
	w.P("	}")
	w.P("	return nil")
	w.P("}")
	w.P("")
}
