// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/note.proto

package bare

import (
	context "context"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	errors "errors"
	uuid "github.com/google/uuid"
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	ormpatch "github.com/protobuf-orm/protobuf-orm/ormpatch"
	apptest "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest"
	ent "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent"
	note "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent/note"
	predicate "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent/predicate"
	entpatch "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entpatch"
	enttx "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/enttx"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

type NoteServiceServer struct {
	Store

	apptest.UnimplementedNoteServiceServer
}

// NewNoteServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewNoteServiceServer(db *ent.Client, opts ...Option) apptest.NoteServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return NoteServiceServer{Store: s.Store}
}

// NoteNarrow answers with `p` and everything else that narrows a
// read of a Note: the rows that have not been erased, and whatever
// `scope` says of those.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func NoteNarrow(ctx context.Context, scope Scope, p predicate.Note) (predicate.Note, error) {
	ps := make([]predicate.Note, 0, 3)

	// A row that was erased is not a row a read answers with.
	ps = append(ps, note.DateErasedIsNil())
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.NoteScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return note.And(ps...), nil
	}
}

// narrow is [NoteNarrow] with this server's own scope.
func (s NoteServiceServer) narrow(ctx context.Context, p predicate.Note) (predicate.Note, error) {
	return NoteNarrow(ctx, s.Scope, p)
}

func (s NoteServiceServer) Add(ctx context.Context, req *apptest.NoteAddRequest) (*apptest.Note, error) {
	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	q := st.Db.Note.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "apptest.Note", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetID(v)
	}
	if req.HasAlias() {
		q.SetAlias(req.GetAlias())
	} else {
		q.SetAlias("")
	}
	if req.HasBody() {
		q.SetBody(req.GetBody())
	} else {
		q.SetBody("")
	}
	if req.HasSlug() {
		q.SetSlug(req.GetSlug())
	} else {
		q.SetSlug("")
	}
	q.SetDateUpdated(st.now())
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(st.now())
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Errorf(codes.AlreadyExists, "Note already exists: %s", err.Unwrap())
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Errorf(codes.NotFound, "Note: referenced entity not found: %s", err.Unwrap())
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  apptest.NoteService_Add_FullMethodName,
		Key: u.ID,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	return u.Proto(), nil
}

func (s NoteServiceServer) Get(ctx context.Context, req *apptest.NoteGetRequest) (*apptest.Note, error) {
	p, err := NotePick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Note.Query().Where(p)
	NoteSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Note not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectNoteKey(q *ent.NoteQuery) {
	q.Select(note.FieldID)
}

func NoteSelectedFields(m *apptest.NoteSelect) []string {
	if m.GetAll() {
		return note.Columns
	}

	vs := make([]string, 0, len(note.Columns))
	{
		vs = append(vs, note.FieldID)
	}
	if m.GetAlias() {
		vs = append(vs, note.FieldAlias)
	}
	if m.GetBody() {
		vs = append(vs, note.FieldBody)
	}
	if m.GetSlug() {
		vs = append(vs, note.FieldSlug)
	}
	if m.GetDateErased() {
		vs = append(vs, note.FieldDateErased)
	}
	if m.GetDateUpdated() {
		vs = append(vs, note.FieldDateUpdated)
	}
	if m.GetDateCreated() {
		vs = append(vs, note.FieldDateCreated)
	}

	return vs
}

func NoteSelect(q *ent.NoteQuery, m *apptest.NoteSelect) {
	if !m.GetAll() {
		fields := NoteSelectedFields(m)
		q.Select(fields...)
	}
}

func NoteSelectInit(q *ent.NoteQuery, m *apptest.NoteSelect) {
	if m != nil {
		NoteSelect(q, m)
	} else {
	}
}

func (s NoteServiceServer) Patch(ctx context.Context, req *apptest.NotePatchRequest) (*apptest.Note, error) {
	doc, err := ormpatch.FromPatchRequest(noteOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, apptest.NoteService_Patch_FullMethodName)
}

func NoteGetKey(ctx context.Context, db *ent.Client, ref *apptest.NoteRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := uuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := NotePick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Note.Query().Where(p).OnlyID(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Note not found")
		}
		return z, err
	}

	return v, nil
}

var noteOrmEntity = ormpatch.MustEntityOf(apptest.File_apptest_note_proto, "Note")

var notePatchColumns = entpatch.Columns{
	1: note.FieldID, 2: note.FieldAlias, 3: note.FieldBody, 4: note.FieldSlug, 13: note.FieldDateErased, 14: note.FieldDateUpdated, 15: note.FieldDateCreated}

func (s NoteServiceServer) Apply(ctx context.Context, req *apptest.NoteApplyRequest) (*apptest.Note, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), apptest.NoteService_Apply_FullMethodName)
}

func (s NoteServiceServer) apply(ctx context.Context, ref *apptest.NoteRef, doc *patchpb.Patch, by string) (*apptest.Note, error) {
	plan := &ormpatch.Plan{Entity: noteOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(noteOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, notePatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := NoteGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &apptest.NoteRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, note.IDEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Note.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Note(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Note.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Note not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Note.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Note(pred))
		}
		q.Modify(mod)
		if !plan.WritesTo(14) {
			q.SetDateUpdated(st.now())
		}
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Errorf(codes.AlreadyExists, "Note already exists: %s", err.Unwrap())
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Errorf(codes.NotFound, "Note: referenced entity not found: %s", err.Unwrap())
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Note.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Note not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s NoteServiceServer) Erase(ctx context.Context, req *apptest.NoteRef) (*apptest.NoteEraseResponse, error) {
	p, err := NotePick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Note.Query().Where(p).OnlyID(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &apptest.NoteEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = note.And(p, note.IDEQ(v))
	}

	u := st.Db.Note.Update().Where(p)
	u.SetDateErased(st.now())
	u.SetDateUpdated(st.now())
	n, err := u.Save(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  apptest.NoteService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &apptest.NoteEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

// NotePick answers with the predicate this reference selects on,
// among the rows that are still here.
//
// Erasure is part of the reference and not only part of a read's scope,
// because a reference to a Note is composed into the reference of
// whatever names one: an index over an edge asks this for a predicate and
// puts it inside `HasNoteWith`, where no narrowing of a Note
// is ever applied. A child of an erased row would otherwise be readable by
// naming its parent.
func NotePick(req *apptest.NoteRef) (predicate.Note, error) {
	p, err := pickNote(req)
	if err != nil {
		return nil, err
	}

	return note.And(note.DateErasedIsNil(), p), nil
}

func pickNote(req *apptest.NoteRef) (predicate.Note, error) {
	switch req.WhichKey() {
	case apptest.NoteRef_Id_case:
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return note.IDEQ(v), nil
		}
	case apptest.NoteRef_Slug_case:
		return note.SlugEQ(req.GetSlug()), nil
	case apptest.NoteRef_Alias_case:
		k := req.GetAlias()
		ps := make([]predicate.Note, 0, 1)
		ps = append(ps, note.AliasEQ(k.GetAlias()))
		return note.And(ps...), nil
	case apptest.NoteRef_Body_case:
		k := req.GetBody()
		ps := make([]predicate.Note, 0, 1)
		ps = append(ps, note.BodyEQ(k.GetBody()))
		return note.And(ps...), nil
	case apptest.NoteRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Note")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
