// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/seat.proto

package bare

import (
	context "context"
	errors "errors"
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	ent1 "github.com/protobuf-orm/ent"
	sqlgraph "github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	graph "github.com/protobuf-orm/protobuf-orm/graph"
	ormpatch "github.com/protobuf-orm/protobuf-orm/ormpatch"
	apptest "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest"
	ent "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent"
	predicate "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent/predicate"
	seat "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent/seat"
	entpatch "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entpatch"
	entuuid "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entuuid"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	uuid "uuid"
)

type SeatServiceServer struct {
	Store

	apptest.UnimplementedSeatServiceServer
}

// NewSeatServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewSeatServiceServer(db *ent.Client, opts ...Option) apptest.SeatServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return SeatServiceServer{Store: s.Store}
}

// SeatNarrow answers with `p` and everything else that narrows a
// read of a Seat, which is whatever `scope` says.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func SeatNarrow(ctx context.Context, scope Scope, p predicate.Seat) (predicate.Seat, error) {
	ps := make([]predicate.Seat, 0, 2)
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.SeatScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return seat.And(ps...), nil
	}
}

// narrow is [SeatNarrow] with this server's own scope.
func (s SeatServiceServer) narrow(ctx context.Context, p predicate.Seat) (predicate.Seat, error) {
	return SeatNarrow(ctx, s.Scope, p)
}

func (s SeatServiceServer) Add(ctx context.Context, req *apptest.SeatAddRequest) (*apptest.Seat, error) {
	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	ds := make([]func(v *apptest.Seat), 0, 3)
	q := st.Db.Seat.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "apptest.Seat", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetId(v)
	}
	if k, err := UserGetKey(ctx, st.Db, req.GetHolder()); err != nil {
		return nil, err
	} else {
		q.SetHolderId(k)
		ds = append(ds, func(v *apptest.Seat) {
			v.SetHolder(apptest.User_builder{Id: k[:]}.Build())
		})
	}
	if k, err := TenantGetKey(ctx, st.Db, req.GetOrg()); err != nil {
		return nil, err
	} else {
		q.SetOrgId(k)
		ds = append(ds, func(v *apptest.Seat) {
			v.SetOrg(apptest.Tenant_builder{Id: k[:]}.Build())
		})
	}
	if req.HasDeputy() {
		if k, err := UserGetKey(ctx, st.Db, req.GetDeputy()); err != nil {
			return nil, err
		} else {
			q.SetDeputyId(k)
			ds = append(ds, func(v *apptest.Seat) {
				v.SetDeputy(apptest.User_builder{Id: k[:]}.Build())
			})
		}
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Error(codes.AlreadyExists, "Seat already exists")
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Error(codes.NotFound, "Seat: referenced entity not found")
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  apptest.SeatService_Add_FullMethodName,
		Key: u.Id,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s SeatServiceServer) Get(ctx context.Context, req *apptest.SeatGetRequest) (*apptest.Seat, error) {
	p, err := SeatPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Seat.Query().Where(p)
	SeatSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Seat not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectSeatKey(q *ent.SeatQuery) {
	q.Select(seat.FieldId)
}

func SeatSelectedFields(m *apptest.SeatSelect) []string {
	if m.GetAll() {
		return seat.Columns
	}

	vs := make([]string, 0, len(seat.Columns))
	{
		vs = append(vs, seat.FieldId)
	}

	return vs
}

func SeatSelect(q *ent.SeatQuery, m *apptest.SeatSelect) {
	if !m.GetAll() {
		fields := SeatSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasHolder() {
		q.WithHolder(func(q *ent.UserQuery) {
			UserSelect(q, m.GetHolder())
		})
	}
	if m.HasOrg() {
		q.WithOrg(func(q *ent.TenantQuery) {
			TenantSelect(q, m.GetOrg())
		})
	}
	if m.HasDeputy() {
		q.WithDeputy(func(q *ent.UserQuery) {
			UserSelect(q, m.GetDeputy())
		})
	}
}

func SeatSelectInit(q *ent.SeatQuery, m *apptest.SeatSelect) {
	if m != nil {
		SeatSelect(q, m)
	} else {
		q.WithHolder(selectUserKey)
		q.WithOrg(selectTenantKey)
		q.WithDeputy(selectUserKey)
	}
}

func (s SeatServiceServer) Patch(ctx context.Context, req *apptest.SeatPatchRequest) (*apptest.Seat, error) {
	doc, err := ormpatch.FromPatchRequest(seatOrmEntity, req.ProtoReflect(), func(ed graph.Edge, ref protoreflect.Message) (protoreflect.Value, error) {
		switch ed.Number() {
		case 2:
			k, err := UserGetKey(ctx, s.Db, ref.Interface().(*apptest.UserRef))
			if err != nil {
				return protoreflect.Value{}, err
			}
			return protoreflect.ValueOfBytes(k[:]), nil
		case 3:
			k, err := TenantGetKey(ctx, s.Db, ref.Interface().(*apptest.TenantRef))
			if err != nil {
				return protoreflect.Value{}, err
			}
			return protoreflect.ValueOfBytes(k[:]), nil
		case 4:
			k, err := UserGetKey(ctx, s.Db, ref.Interface().(*apptest.UserRef))
			if err != nil {
				return protoreflect.Value{}, err
			}
			return protoreflect.ValueOfBytes(k[:]), nil
		}
		return protoreflect.Value{}, status.Errorf(codes.Internal, "no key resolver for edge: %s", ed.Name())
	})
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, apptest.SeatService_Patch_FullMethodName)
}

func SeatGetKey(ctx context.Context, db *ent.Client, ref *apptest.SeatRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := entuuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := SeatPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Seat.Query().Where(p).OnlyId(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Seat not found")
		}
		return z, err
	}

	return v, nil
}

var seatOrmEntity = ormpatch.MustEntityOf(apptest.File_apptest_seat_proto, "Seat")

var seatPatchColumns = entpatch.Columns{
	1: seat.FieldId, 2: seat.HolderColumn, 3: seat.OrgColumn, 4: seat.DeputyColumn}

func (s SeatServiceServer) Apply(ctx context.Context, req *apptest.SeatApplyRequest) (*apptest.Seat, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), apptest.SeatService_Apply_FullMethodName)
}

func (s SeatServiceServer) apply(ctx context.Context, ref *apptest.SeatRef, doc *patchpb.Patch, by string) (*apptest.Seat, error) {
	plan := &ormpatch.Plan{Entity: seatOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(seatOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, seatPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := SeatGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &apptest.SeatRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, seat.IdEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Seat.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Seat(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Seat.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Seat not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Seat.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Seat(pred))
		}
		q.Modify(mod)
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Error(codes.AlreadyExists, "Seat already exists")
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Error(codes.NotFound, "Seat: referenced entity not found")
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Seat.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Seat not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s SeatServiceServer) Erase(ctx context.Context, req *apptest.SeatRef) (*apptest.SeatEraseResponse, error) {
	p, err := SeatPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Seat.Query().Where(p).OnlyId(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &apptest.SeatEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = seat.And(p, seat.IdEQ(v))
	}

	n, err := st.Db.Seat.Delete().Where(p).Exec(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  apptest.SeatService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &apptest.SeatEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

func SeatPick(req *apptest.SeatRef) (predicate.Seat, error) {
	switch req.WhichKey() {
	case apptest.SeatRef_Id_case:
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return seat.IdEQ(v), nil
		}
	case apptest.SeatRef_Place_case:
		k := req.GetPlace()
		ps := make([]predicate.Seat, 0, 2)
		if p, err := UserPick(k.GetHolder()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "place.holder: %s", err)
		} else {
			ps = append(ps, seat.HasHolderWith(p))
		}
		if p, err := TenantPick(k.GetOrg()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "place.org: %s", err)
		} else {
			ps = append(ps, seat.HasOrgWith(p))
		}
		return seat.And(ps...), nil
	case apptest.SeatRef_Deputy_case:
		k := req.GetDeputy()
		ps := make([]predicate.Seat, 0, 1)
		if p, err := UserPick(k.GetDeputy()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "deputy.deputy: %s", err)
		} else {
			ps = append(ps, seat.HasDeputyWith(p))
		}
		return seat.And(ps...), nil
	case apptest.SeatRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Seat")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
