// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/shift.proto

package bare

import (
	context "context"
	errors "errors"
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	ent1 "github.com/protobuf-orm/ent"
	sqlgraph "github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	ormpatch "github.com/protobuf-orm/protobuf-orm/ormpatch"
	apptest "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest"
	ent "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent"
	predicate "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent/predicate"
	shift "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent/shift"
	entpatch "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entpatch"
	entuuid "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entuuid"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	uuid "uuid"
)

type ShiftServiceServer struct {
	Store

	apptest.UnimplementedShiftServiceServer
}

// NewShiftServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewShiftServiceServer(db *ent.Client, opts ...Option) apptest.ShiftServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return ShiftServiceServer{Store: s.Store}
}

// ShiftNarrow answers with `p` and everything else that narrows a
// read of a Shift, which is whatever `scope` says.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func ShiftNarrow(ctx context.Context, scope Scope, p predicate.Shift) (predicate.Shift, error) {
	ps := make([]predicate.Shift, 0, 2)
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.ShiftScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return shift.And(ps...), nil
	}
}

// narrow is [ShiftNarrow] with this server's own scope.
func (s ShiftServiceServer) narrow(ctx context.Context, p predicate.Shift) (predicate.Shift, error) {
	return ShiftNarrow(ctx, s.Scope, p)
}

func (s ShiftServiceServer) Add(ctx context.Context, req *apptest.ShiftAddRequest) (*apptest.Shift, error) {
	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	q := st.Db.Shift.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "apptest.Shift", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetId(v)
	}
	q.SetDesk(req.GetDesk())
	q.SetStartsAt(req.GetStartsAt().AsTime())

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Error(codes.AlreadyExists, "Shift already exists")
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Error(codes.NotFound, "Shift: referenced entity not found")
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  apptest.ShiftService_Add_FullMethodName,
		Key: u.Id,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	return u.Proto(), nil
}

func (s ShiftServiceServer) Get(ctx context.Context, req *apptest.ShiftGetRequest) (*apptest.Shift, error) {
	p, err := ShiftPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Shift.Query().Where(p)
	ShiftSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Shift not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectShiftKey(q *ent.ShiftQuery) {
	q.Select(shift.FieldId)
}

func ShiftSelectedFields(m *apptest.ShiftSelect) []string {
	if m.GetAll() {
		return shift.Columns
	}

	vs := make([]string, 0, len(shift.Columns))
	{
		vs = append(vs, shift.FieldId)
	}
	if m.GetDesk() {
		vs = append(vs, shift.FieldDesk)
	}
	if m.GetStartsAt() {
		vs = append(vs, shift.FieldStartsAt)
	}

	return vs
}

func ShiftSelect(q *ent.ShiftQuery, m *apptest.ShiftSelect) {
	if !m.GetAll() {
		fields := ShiftSelectedFields(m)
		q.Select(fields...)
	}
}

func ShiftSelectInit(q *ent.ShiftQuery, m *apptest.ShiftSelect) {
	if m != nil {
		ShiftSelect(q, m)
	} else {
	}
}

func (s ShiftServiceServer) Patch(ctx context.Context, req *apptest.ShiftPatchRequest) (*apptest.Shift, error) {
	doc, err := ormpatch.FromPatchRequest(shiftOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, apptest.ShiftService_Patch_FullMethodName)
}

func ShiftGetKey(ctx context.Context, db *ent.Client, ref *apptest.ShiftRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := entuuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := ShiftPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Shift.Query().Where(p).OnlyId(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Shift not found")
		}
		return z, err
	}

	return v, nil
}

var shiftOrmEntity = ormpatch.MustEntityOf(apptest.File_apptest_shift_proto, "Shift")

var shiftPatchColumns = entpatch.Columns{
	1: shift.FieldId, 2: shift.FieldDesk, 3: shift.FieldStartsAt}

func (s ShiftServiceServer) Apply(ctx context.Context, req *apptest.ShiftApplyRequest) (*apptest.Shift, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), apptest.ShiftService_Apply_FullMethodName)
}

func (s ShiftServiceServer) apply(ctx context.Context, ref *apptest.ShiftRef, doc *patchpb.Patch, by string) (*apptest.Shift, error) {
	plan := &ormpatch.Plan{Entity: shiftOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(shiftOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, shiftPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := ShiftGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &apptest.ShiftRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, shift.IdEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Shift.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Shift(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Shift.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Shift not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Shift.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Shift(pred))
		}
		q.Modify(mod)
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Error(codes.AlreadyExists, "Shift already exists")
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Error(codes.NotFound, "Shift: referenced entity not found")
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Shift.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Shift not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s ShiftServiceServer) Erase(ctx context.Context, req *apptest.ShiftRef) (*apptest.ShiftEraseResponse, error) {
	p, err := ShiftPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Shift.Query().Where(p).OnlyId(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &apptest.ShiftEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = shift.And(p, shift.IdEQ(v))
	}

	n, err := st.Db.Shift.Delete().Where(p).Exec(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  apptest.ShiftService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &apptest.ShiftEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

func ShiftPick(req *apptest.ShiftRef) (predicate.Shift, error) {
	switch req.WhichKey() {
	case apptest.ShiftRef_Id_case:
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return shift.IdEQ(v), nil
		}
	case apptest.ShiftRef_Slot_case:
		k := req.GetSlot()
		ps := make([]predicate.Shift, 0, 2)
		ps = append(ps, shift.DeskEQ(k.GetDesk()))
		ps = append(ps, shift.StartsAtEQ(k.GetStartsAt().AsTime()))
		return shift.And(ps...), nil
	case apptest.ShiftRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Shift")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
