// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package bare

import (
	apptest "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest"
	ent "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent"
)

type Server struct {
	Db *ent.Client
}

func NewServer(db *ent.Client) Server {
	return Server{Db: db}
}

func (s Server) ValueField() apptest.ValueFieldServiceServer { return NewValueFieldServiceServer(s.Db) }
func (s Server) MessageField() apptest.MessageFieldServiceServer {
	return NewMessageFieldServiceServer(s.Db)
}
func (s Server) MapField() apptest.MapFieldServiceServer { return NewMapFieldServiceServer(s.Db) }
func (s Server) Tenant() apptest.TenantServiceServer     { return NewTenantServiceServer(s.Db) }
func (s Server) User() apptest.UserServiceServer         { return NewUserServiceServer(s.Db) }
