// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/tenant.proto

package bare

import (
	context "context"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	errors "errors"
	uuid "github.com/google/uuid"
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	ormpatch "github.com/protobuf-orm/protobuf-orm/ormpatch"
	apptest "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest"
	ent "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent"
	predicate "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent/predicate"
	tenant "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent/tenant"
	entpatch "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entpatch"
	enttx "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/enttx"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type TenantServiceServer struct {
	Store

	apptest.UnimplementedTenantServiceServer
}

// NewTenantServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewTenantServiceServer(db *ent.Client, opts ...Option) apptest.TenantServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return TenantServiceServer{Store: s.Store}
}

// TenantNarrow answers with `p` and everything else that narrows a
// read of a Tenant, which is whatever `scope` says.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func TenantNarrow(ctx context.Context, scope Scope, p predicate.Tenant) (predicate.Tenant, error) {
	ps := make([]predicate.Tenant, 0, 2)
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.TenantScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return tenant.And(ps...), nil
	}
}

// narrow is [TenantNarrow] with this server's own scope.
func (s TenantServiceServer) narrow(ctx context.Context, p predicate.Tenant) (predicate.Tenant, error) {
	return TenantNarrow(ctx, s.Scope, p)
}

func (s TenantServiceServer) Add(ctx context.Context, req *apptest.TenantAddRequest) (*apptest.Tenant, error) {
	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	q := st.Db.Tenant.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "apptest.Tenant", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetID(v)
	}
	if req.HasAlias() {
		q.SetAlias(req.GetAlias())
	} else {
		q.SetAlias("")
	}
	if req.HasName() {
		q.SetName(req.GetName())
	} else {
		q.SetName("")
	}
	if u := req.GetLabels(); len(u) > 0 {
		q.SetLabels(u)
	}
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(st.now())
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Errorf(codes.AlreadyExists, "Tenant already exists: %s", err.Unwrap())
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Errorf(codes.NotFound, "Tenant: referenced entity not found: %s", err.Unwrap())
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  apptest.TenantService_Add_FullMethodName,
		Key: u.ID,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	return u.Proto(), nil
}

func (s TenantServiceServer) Get(ctx context.Context, req *apptest.TenantGetRequest) (*apptest.Tenant, error) {
	p, err := TenantPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Tenant.Query().Where(p)
	TenantSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Tenant not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectTenantKey(q *ent.TenantQuery) {
	q.Select(tenant.FieldID)
}

func TenantSelectedFields(m *apptest.TenantSelect) []string {
	if m.GetAll() {
		return tenant.Columns
	}

	vs := make([]string, 0, len(tenant.Columns))
	{
		vs = append(vs, tenant.FieldID)
	}
	if m.GetAlias() {
		vs = append(vs, tenant.FieldAlias)
	}
	if m.GetName() {
		vs = append(vs, tenant.FieldName)
	}
	if m.GetLabels() {
		vs = append(vs, tenant.FieldLabels)
	}
	if m.GetDateCreated() {
		vs = append(vs, tenant.FieldDateCreated)
	}

	return vs
}

func TenantSelect(q *ent.TenantQuery, m *apptest.TenantSelect) {
	if !m.GetAll() {
		fields := TenantSelectedFields(m)
		q.Select(fields...)
	}
}

func TenantSelectInit(q *ent.TenantQuery, m *apptest.TenantSelect) {
	if m != nil {
		TenantSelect(q, m)
	} else {
	}
}

func (s TenantServiceServer) Patch(ctx context.Context, req *apptest.TenantPatchRequest) (*apptest.Tenant, error) {
	doc, err := ormpatch.FromPatchRequest(tenantOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, apptest.TenantService_Patch_FullMethodName)
}

func TenantGetKey(ctx context.Context, db *ent.Client, ref *apptest.TenantRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := uuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := TenantPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Tenant.Query().Where(p).OnlyID(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Tenant not found")
		}
		return z, err
	}

	return v, nil
}

var tenantOrmEntity = ormpatch.MustEntityOf(apptest.File_apptest_tenant_proto, "Tenant")

var tenantPatchColumns = entpatch.Columns{
	1: tenant.FieldID, 4: tenant.FieldAlias, 5: tenant.FieldName, 7: tenant.FieldLabels, 15: tenant.FieldDateCreated}

func (s TenantServiceServer) Apply(ctx context.Context, req *apptest.TenantApplyRequest) (*apptest.Tenant, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), apptest.TenantService_Apply_FullMethodName)
}

func (s TenantServiceServer) apply(ctx context.Context, ref *apptest.TenantRef, doc *patchpb.Patch, by string) (*apptest.Tenant, error) {
	plan := &ormpatch.Plan{Entity: tenantOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(tenantOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, tenantPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := TenantGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &apptest.TenantRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, tenant.IDEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Tenant.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Tenant(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Tenant.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Tenant not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Tenant.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Tenant(pred))
		}
		q.Modify(mod)
		if n, err := q.Save(ctx); err != nil {
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Tenant.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Tenant not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s TenantServiceServer) Erase(ctx context.Context, req *apptest.TenantRef) (*emptypb.Empty, error) {
	p, err := TenantPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Tenant.Query().Where(p).OnlyID(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &emptypb.Empty{}, nil
			}
			return nil, err
		}

		k = v
		p = tenant.IDEQ(v)
	}

	n, err := st.Db.Tenant.Delete().Where(p).Exec(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  apptest.TenantService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return &emptypb.Empty{}, nil
}

func TenantPick(req *apptest.TenantRef) (predicate.Tenant, error) {
	switch req.WhichKey() {
	case apptest.TenantRef_Id_case:
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return tenant.IDEQ(v), nil
		}
	case apptest.TenantRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Tenant")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
