// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/tenant.proto

package bare

import (
	context "context"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	uuid "github.com/google/uuid"
	apptest "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest"
	ent "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent"
	predicate "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent/predicate"
	tenant "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent/tenant"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	time "time"
)

type TenantServiceServer struct {
	Db *ent.Client
	apptest.UnimplementedTenantServiceServer
}

func NewTenantServiceServer(db *ent.Client) apptest.TenantServiceServer {
	return TenantServiceServer{Db: db}
}

func (s TenantServiceServer) Add(ctx context.Context, req *apptest.TenantAddRequest) (*apptest.Tenant, error) {
	q := s.Db.Tenant.Create()
	if req.HasId() {
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			q.SetID(v)
		}
	} else {
		q.SetID(uuid.New())
	}
	if req.HasAlias() {
		q.SetAlias(req.GetAlias())
	} else {
		q.SetAlias("")
	}
	if req.HasName() {
		q.SetName(req.GetName())
	} else {
		q.SetName("")
	}
	if u := req.GetLabels(); len(u) > 0 {
		q.SetLabels(u)
	}
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(time.Now().UTC())
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok && sqlgraph.IsUniqueConstraintError(err) {
			return nil, status.Errorf(codes.AlreadyExists, "Tenant already exists: %s", err.Unwrap())
		}
		return nil, err
	}

	return u.Proto(), nil
}

func (s TenantServiceServer) Get(ctx context.Context, req *apptest.TenantGetRequest) (*apptest.Tenant, error) {
	q := s.Db.Tenant.Query()

	if p, err := TenantPick(req.GetRef()); err != nil {
		return nil, err
	} else {
		q.Where(p)
	}
	TenantSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Tenant not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectTenantKey(q *ent.TenantQuery) {
	q.Select(tenant.FieldID)
}

func TenantSelectedFields(m *apptest.TenantSelect) []string {
	if m.GetAll() {
		return tenant.Columns
	}

	vs := make([]string, 0, len(tenant.Columns))
	{
		vs = append(vs, tenant.FieldID)
	}
	if m.GetAlias() {
		vs = append(vs, tenant.FieldAlias)
	}
	if m.GetName() {
		vs = append(vs, tenant.FieldName)
	}
	if m.GetLabels() {
		vs = append(vs, tenant.FieldLabels)
	}
	if m.GetDateCreated() {
		vs = append(vs, tenant.FieldDateCreated)
	}

	return vs
}

func TenantSelect(q *ent.TenantQuery, m *apptest.TenantSelect) {
	if !m.GetAll() {
		fields := TenantSelectedFields(m)
		q.Select(fields...)
	}
}

func TenantSelectInit(q *ent.TenantQuery, m *apptest.TenantSelect) {
	if m != nil {
		TenantSelect(q, m)
	} else {
	}
}

func (s TenantServiceServer) Patch(ctx context.Context, req *apptest.TenantPatchRequest) (*apptest.Tenant, error) {
	p, err := TenantPick(req.GetRef())
	if err != nil {
		return nil, err
	}

	q := s.Db.Tenant.Update().Where(p)
	if req.HasAlias() {
		q.SetAlias(req.GetAlias())
	}
	if req.HasName() {
		q.SetName(req.GetName())
	}
	if u := req.GetLabels(); len(u) > 0 {
		q.SetLabels(u)
	}

	if n, err := q.Save(ctx); err != nil {
		return nil, err
	} else if n == 0 {
		return nil, status.Errorf(codes.NotFound, "not found")
	}

	return s.Get(ctx, req.GetRef().Pick())
}

func TenantGetKey(ctx context.Context, db *ent.Client, ref *apptest.TenantRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := uuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := TenantPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Tenant.Query().Where(p).OnlyID(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Tenant not found")
		}
		return z, err
	}

	return v, nil
}

func (s TenantServiceServer) Erase(ctx context.Context, req *apptest.TenantRef) (*emptypb.Empty, error) {
	p, err := TenantPick(req)
	if err != nil {
		return nil, err
	}

	if _, err := s.Db.Tenant.Delete().Where(p).Exec(ctx); err != nil {
		return nil, err
	}
	return nil, nil
}

func TenantPick(req *apptest.TenantRef) (predicate.Tenant, error) {
	switch req.WhichKey() {
	case apptest.TenantRef_Id_case:
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return tenant.IDEQ(v), nil
		}
	case apptest.TenantRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Tenant")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
