// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/user.proto

package ent

import (
	apptest "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest"
	ent "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent"
)

type UserServiceServer struct {
	Db *ent.Client
	apptest.UnimplementedUserServiceServer
}

func NewUserServiceServer(db *ent.Client) UserServiceServer {
	return UserServiceServer{Db: db}
}
