// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/user.proto

package bare

import (
	context "context"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	errors "errors"
	uuid "github.com/google/uuid"
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	graph "github.com/protobuf-orm/protobuf-orm/graph"
	ormpatch "github.com/protobuf-orm/protobuf-orm/ormpatch"
	apptest "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest"
	ent "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent"
	predicate "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent/predicate"
	user "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest/ent/user"
	entpatch "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entpatch"
	enttx "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/enttx"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type UserServiceServer struct {
	Store

	apptest.UnimplementedUserServiceServer
}

// NewUserServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewUserServiceServer(db *ent.Client, opts ...Option) apptest.UserServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return UserServiceServer{Store: s.Store}
}

// UserNarrow answers with `p` and everything else that narrows a
// read of a User, which is whatever `scope` says.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func UserNarrow(ctx context.Context, scope Scope, p predicate.User) (predicate.User, error) {
	ps := make([]predicate.User, 0, 2)
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.UserScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return user.And(ps...), nil
	}
}

// narrow is [UserNarrow] with this server's own scope.
func (s UserServiceServer) narrow(ctx context.Context, p predicate.User) (predicate.User, error) {
	return UserNarrow(ctx, s.Scope, p)
}

func (s UserServiceServer) Add(ctx context.Context, req *apptest.UserAddRequest) (*apptest.User, error) {
	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	ds := make([]func(v *apptest.User), 0, 1)
	q := st.Db.User.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "apptest.User", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetID(v)
	}
	if k, err := TenantGetKey(ctx, st.Db, req.GetTenant()); err != nil {
		return nil, err
	} else {
		q.SetTenantID(k)
		ds = append(ds, func(v *apptest.User) {
			v.SetTenant(apptest.Tenant_builder{Id: k[:]}.Build())
		})
	}
	if req.HasAlias() {
		q.SetAlias(req.GetAlias())
	} else {
		q.SetAlias("")
	}
	if req.HasName() {
		q.SetName(req.GetName())
	} else {
		q.SetName("")
	}
	if u := req.GetLabels(); len(u) > 0 {
		q.SetLabels(u)
	}
	if req.HasLock() {
		q.SetLock(req.GetLock())
	}
	q.SetDateUpdated(st.now())
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(st.now())
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Errorf(codes.AlreadyExists, "User already exists: %s", err.Unwrap())
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Errorf(codes.NotFound, "User: referenced entity not found: %s", err.Unwrap())
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  apptest.UserService_Add_FullMethodName,
		Key: u.ID,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s UserServiceServer) Get(ctx context.Context, req *apptest.UserGetRequest) (*apptest.User, error) {
	p, err := UserPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.User.Query().Where(p)
	UserSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "User not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectUserKey(q *ent.UserQuery) {
	q.Select(user.FieldID)
}

func UserSelectedFields(m *apptest.UserSelect) []string {
	if m.GetAll() {
		return user.Columns
	}

	vs := make([]string, 0, len(user.Columns))
	{
		vs = append(vs, user.FieldID)
	}
	if m.GetAlias() {
		vs = append(vs, user.FieldAlias)
	}
	if m.GetName() {
		vs = append(vs, user.FieldName)
	}
	if m.GetLabels() {
		vs = append(vs, user.FieldLabels)
	}
	if m.GetLock() {
		vs = append(vs, user.FieldLock)
	}
	if m.GetDateUpdated() {
		vs = append(vs, user.FieldDateUpdated)
	}
	if m.GetDateCreated() {
		vs = append(vs, user.FieldDateCreated)
	}

	return vs
}

func UserSelect(q *ent.UserQuery, m *apptest.UserSelect) {
	if !m.GetAll() {
		fields := UserSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasTenant() {
		q.WithTenant(func(q *ent.TenantQuery) {
			TenantSelect(q, m.GetTenant())
		})
	}
}

func UserSelectInit(q *ent.UserQuery, m *apptest.UserSelect) {
	if m != nil {
		UserSelect(q, m)
	} else {
		q.WithTenant(selectTenantKey)
	}
}

func (s UserServiceServer) Patch(ctx context.Context, req *apptest.UserPatchRequest) (*apptest.User, error) {
	doc, err := ormpatch.FromPatchRequest(userOrmEntity, req.ProtoReflect(), func(ed graph.Edge, ref protoreflect.Message) (protoreflect.Value, error) {
		switch ed.Number() {
		case 2:
			k, err := TenantGetKey(ctx, s.Db, ref.Interface().(*apptest.TenantRef))
			if err != nil {
				return protoreflect.Value{}, err
			}
			return protoreflect.ValueOfBytes(k[:]), nil
		}
		return protoreflect.Value{}, status.Errorf(codes.Internal, "no key resolver for edge: %s", ed.Name())
	})
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, apptest.UserService_Patch_FullMethodName)
}

func UserGetKey(ctx context.Context, db *ent.Client, ref *apptest.UserRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := uuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := UserPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.User.Query().Where(p).OnlyID(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "User not found")
		}
		return z, err
	}

	return v, nil
}

var userOrmEntity = ormpatch.MustEntityOf(apptest.File_apptest_user_proto, "User")

var userPatchColumns = entpatch.Columns{
	1: user.FieldID, 2: user.TenantColumn, 4: user.FieldAlias, 5: user.FieldName, 7: user.FieldLabels, 8: user.FieldLock, 14: user.FieldDateUpdated, 15: user.FieldDateCreated}

func (s UserServiceServer) Apply(ctx context.Context, req *apptest.UserApplyRequest) (*apptest.User, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), apptest.UserService_Apply_FullMethodName)
}

func (s UserServiceServer) apply(ctx context.Context, ref *apptest.UserRef, doc *patchpb.Patch, by string) (*apptest.User, error) {
	plan := &ormpatch.Plan{Entity: userOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(userOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, userPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := UserGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &apptest.UserRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, user.IDEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.User.Query().Where(p)
		if pred != nil {
			q.Where(predicate.User(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.User.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "User not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.User.Update().Where(p)
		if pred != nil {
			q.Where(predicate.User(pred))
		}
		q.Modify(mod)
		if !plan.WritesTo(14) {
			q.SetDateUpdated(st.now())
		}
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Errorf(codes.AlreadyExists, "User already exists: %s", err.Unwrap())
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Errorf(codes.NotFound, "User: referenced entity not found: %s", err.Unwrap())
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.User.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "User not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s UserServiceServer) Erase(ctx context.Context, req *apptest.UserRef) (*emptypb.Empty, error) {
	p, err := UserPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.User.Query().Where(p).OnlyID(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &emptypb.Empty{}, nil
			}
			return nil, err
		}

		k = v
		p = user.IDEQ(v)
	}

	n, err := st.Db.User.Delete().Where(p).Exec(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  apptest.UserService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return &emptypb.Empty{}, nil
}

func UserPick(req *apptest.UserRef) (predicate.User, error) {
	switch req.WhichKey() {
	case apptest.UserRef_Id_case:
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return user.IDEQ(v), nil
		}
	case apptest.UserRef_Alias_case:
		k := req.GetAlias()
		ps := make([]predicate.User, 0, 2)
		ps = append(ps, user.AliasEQ(k.GetAlias()))
		if p, err := TenantPick(k.GetTenant()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "alias.tenant: %s", err)
		} else {
			ps = append(ps, user.HasTenantWith(p))
		}
		return user.And(ps...), nil
	case apptest.UserRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: User")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
