// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/field.proto

package schema

import (
	ent "entgo.io/ent"
	entsql "entgo.io/ent/dialect/entsql"
	schema "entgo.io/ent/schema"
	field "entgo.io/ent/schema/field"
	apptest "github.com/protobuf-orm/protoc-gen-orm-ent/internal/apptest"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

type ValueField struct {
	ent.Schema
}

func (ValueField) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").
			Unique().
			Immutable(),
		field.Float("implicit_f64"),
		field.Float32("implicit_f32"),
		field.Int32("implicit_i32"),
		field.Int64("implicit_i64"),
		field.Uint32("implicit_u32"),
		field.Uint64("implicit_u64"),
		field.Int32("implicit_si32"),
		field.Int64("implicit_si64"),
		field.Uint32("implicit_fi32"),
		field.Uint64("implicit_fi64"),
		field.Int32("implicit_sfi32"),
		field.Int64("implicit_sfi64"),
		field.Bool("implicit_bool"),
		field.String("implicit_string"),
		field.Bytes("implicit_bytes"),
		field.Int32("implicit_enum"),
		field.Float("explicit_f64").
			Nillable().
			Optional(),
		field.Float32("explicit_f32").
			Nillable().
			Optional(),
		field.Int32("explicit_i32").
			Nillable().
			Optional(),
		field.Int64("explicit_i64").
			Nillable().
			Optional(),
		field.Uint32("explicit_u32").
			Nillable().
			Optional(),
		field.Uint64("explicit_u64").
			Nillable().
			Optional(),
		field.Int32("explicit_si32").
			Nillable().
			Optional(),
		field.Int64("explicit_si64").
			Nillable().
			Optional(),
		field.Uint32("explicit_fi32").
			Nillable().
			Optional(),
		field.Uint64("explicit_fi64").
			Nillable().
			Optional(),
		field.Int32("explicit_sfi32").
			Nillable().
			Optional(),
		field.Int64("explicit_sfi64").
			Nillable().
			Optional(),
		field.Bool("explicit_bool").
			Nillable().
			Optional(),
		field.String("explicit_string").
			Nillable().
			Optional(),
		field.Bytes("explicit_bytes").
			Nillable().
			Optional(),
		field.Int32("explicit_enum").
			Nillable().
			Optional(),
		field.JSON("implicit_f64s", []float64{}).
			Optional(),
		field.JSON("implicit_f32s", []float32{}).
			Optional(),
		field.JSON("implicit_i32s", []int32{}).
			Optional(),
		field.JSON("implicit_i64s", []int64{}).
			Optional(),
		field.JSON("implicit_u32s", []uint32{}).
			Optional(),
		field.JSON("implicit_u64s", []uint64{}).
			Optional(),
		field.JSON("implicit_si32s", []int32{}).
			Optional(),
		field.JSON("implicit_si64s", []int64{}).
			Optional(),
		field.JSON("implicit_fi32s", []uint32{}).
			Optional(),
		field.JSON("implicit_fi64s", []uint64{}).
			Optional(),
		field.JSON("implicit_sfi32s", []int32{}).
			Optional(),
		field.JSON("implicit_sfi64s", []int64{}).
			Optional(),
		field.JSON("implicit_bools", []bool{}).
			Optional(),
		field.JSON("implicit_strings", []string{}).
			Optional(),
		field.JSON("implicit_bytess", [][]byte{}).
			Optional(),
		field.JSON("implicit_levels", []apptest.Level{}).
			Optional(),
		field.Float("nullable_f64").
			Nillable().
			Optional(),
		field.Float32("nullable_f32").
			Nillable().
			Optional(),
		field.Int32("nullable_i32").
			Nillable().
			Optional(),
		field.Int64("nullable_i64").
			Nillable().
			Optional(),
		field.Uint32("nullable_u32").
			Nillable().
			Optional(),
		field.Uint64("nullable_u64").
			Nillable().
			Optional(),
		field.Int32("nullable_si32").
			Nillable().
			Optional(),
		field.Int64("nullable_si64").
			Nillable().
			Optional(),
		field.Uint32("nullable_fi32").
			Nillable().
			Optional(),
		field.Uint64("nullable_fi64").
			Nillable().
			Optional(),
		field.Int32("nullable_sfi32").
			Nillable().
			Optional(),
		field.Int64("nullable_sfi64").
			Nillable().
			Optional(),
		field.Bool("nullable_bool").
			Nillable().
			Optional(),
		field.String("nullable_string").
			Nillable().
			Optional(),
		field.Bytes("nullable_bytes").
			Nillable().
			Optional(),
		field.Int32("nullable_level").
			Nillable().
			Optional(),
		field.Float("implicit_f64_with_default").
			Optional(),
		field.Float32("implicit_f32_with_default").
			Optional(),
		field.Int32("implicit_i32_with_default").
			Optional(),
		field.Int64("implicit_i64_with_default").
			Optional(),
		field.Uint32("implicit_u32_with_default").
			Optional(),
		field.Uint64("implicit_u64_with_default").
			Optional(),
		field.Int32("implicit_si32_with_default").
			Optional(),
		field.Int64("implicit_si64_with_default").
			Optional(),
		field.Uint32("implicit_fi32_with_default").
			Optional(),
		field.Uint64("implicit_fi64_with_default").
			Optional(),
		field.Int32("implicit_sfi32_with_default").
			Optional(),
		field.Int64("implicit_sfi64_with_default").
			Optional(),
		field.Bool("implicit_bool_with_default").
			Optional(),
		field.String("implicit_string_with_default").
			Optional(),
		field.Bytes("implicit_bytes_with_default").
			Optional(),
		field.Int32("implicit_level_with_default").
			Optional(),
		field.Float("explicit_f64_with_default").
			Nillable().
			Optional(),
		field.Float32("explicit_f32_with_default").
			Nillable().
			Optional(),
		field.Int32("explicit_i32_with_default").
			Nillable().
			Optional(),
		field.Int64("explicit_i64_with_default").
			Nillable().
			Optional(),
		field.Uint32("explicit_u32_with_default").
			Nillable().
			Optional(),
		field.Uint64("explicit_u64_with_default").
			Nillable().
			Optional(),
		field.Int32("explicit_si32_with_default").
			Nillable().
			Optional(),
		field.Int64("explicit_si64_with_default").
			Nillable().
			Optional(),
		field.Uint32("explicit_fi32_with_default").
			Nillable().
			Optional(),
		field.Uint64("explicit_fi64_with_default").
			Nillable().
			Optional(),
		field.Int32("explicit_sfi32_with_default").
			Nillable().
			Optional(),
		field.Int64("explicit_sfi64_with_default").
			Nillable().
			Optional(),
		field.Bool("explicit_bool_with_default").
			Nillable().
			Optional(),
		field.String("explicit_string_with_default").
			Nillable().
			Optional(),
		field.Bytes("explicit_bytes_with_default").
			Nillable().
			Optional(),
		field.Int32("explicit_level_with_default").
			Nillable().
			Optional(),
		field.Float("implicit_immutable_f64").
			Immutable(),
		field.Float32("implicit_immutable_f32").
			Immutable(),
		field.Int32("implicit_immutable_i32").
			Immutable(),
		field.Int64("implicit_immutable_i64").
			Immutable(),
		field.Uint32("implicit_immutable_u32").
			Immutable(),
		field.Uint64("implicit_immutable_u64").
			Immutable(),
		field.Int32("implicit_immutable_si32").
			Immutable(),
		field.Int64("implicit_immutable_si64").
			Immutable(),
		field.Uint32("implicit_immutable_fi32").
			Immutable(),
		field.Uint64("implicit_immutable_fi64").
			Immutable(),
		field.Int32("implicit_immutable_sfi32").
			Immutable(),
		field.Int64("implicit_immutable_sfi64").
			Immutable(),
		field.Bool("implicit_immutable_bool").
			Immutable(),
		field.String("implicit_immutable_string").
			Immutable(),
		field.Bytes("implicit_immutable_bytes").
			Immutable(),
		field.Int32("implicit_immutable_level").
			Immutable(),
		field.Float("explicit_immutable_f64").
			Nillable().
			Immutable().
			Optional(),
		field.Float32("explicit_immutable_f32").
			Nillable().
			Immutable().
			Optional(),
		field.Int32("explicit_immutable_i32").
			Nillable().
			Immutable().
			Optional(),
		field.Int64("explicit_immutable_i64").
			Nillable().
			Immutable().
			Optional(),
		field.Uint32("explicit_immutable_u32").
			Nillable().
			Immutable().
			Optional(),
		field.Uint64("explicit_immutable_u64").
			Nillable().
			Immutable().
			Optional(),
		field.Int32("explicit_immutable_si32").
			Nillable().
			Immutable().
			Optional(),
		field.Int64("explicit_immutable_si64").
			Nillable().
			Immutable().
			Optional(),
		field.Uint32("explicit_immutable_fi32").
			Nillable().
			Immutable().
			Optional(),
		field.Uint64("explicit_immutable_fi64").
			Nillable().
			Immutable().
			Optional(),
		field.Int32("explicit_immutable_sfi32").
			Nillable().
			Immutable().
			Optional(),
		field.Int64("explicit_immutable_sfi64").
			Nillable().
			Immutable().
			Optional(),
		field.Bool("explicit_immutable_bool").
			Nillable().
			Immutable().
			Optional(),
		field.String("explicit_immutable_string").
			Nillable().
			Immutable().
			Optional(),
		field.Bytes("explicit_immutable_bytes").
			Nillable().
			Immutable().
			Optional(),
		field.Int32("explicit_immutable_level").
			Nillable().
			Immutable().
			Optional(),
	}
}

func (ValueField) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "valuefield"},
	}
}

type MessageField struct {
	ent.Schema
}

func (MessageField) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").
			Unique().
			Immutable(),
		field.JSON("explicit", &structpb.Struct{}).
			Optional(),
		field.JSON("repeated", []*structpb.Struct{}).
			Optional(),
		field.JSON("nullable", &structpb.Struct{}).
			Optional(),
		field.JSON("explicit_with_default", &structpb.Struct{}).
			Optional(),
		field.JSON("explicit_immutable", &structpb.Struct{}).
			Immutable().
			Optional(),
	}
}

func (MessageField) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "messagefield"},
	}
}

type MapField struct {
	ent.Schema
}

func (MapField) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").
			Unique().
			Immutable(),
		field.JSON("implicit_string", map[string]string{}).
			Optional(),
		field.JSON("implicit_enum", map[string]apptest.Level{}).
			Optional(),
		field.JSON("implicit_json", map[string]*structpb.Struct{}).
			Optional(),
		field.JSON("implicit_string_with_default", map[string]string{}).
			Optional(),
		field.JSON("implicit_enum_with_default", map[string]apptest.Level{}).
			Optional(),
		field.JSON("implicit_json_with_default", map[string]*structpb.Struct{}).
			Optional(),
		field.JSON("implicit_immutable_string", map[string]string{}).
			Immutable().
			Optional(),
		field.JSON("implicit_immutable_enum", map[string]apptest.Level{}).
			Immutable().
			Optional(),
		field.JSON("implicit_immutable_json", map[string]*structpb.Struct{}).
			Immutable().
			Optional(),
	}
}

func (MapField) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "mapfield"},
	}
}
