// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/note.proto

package schema

import (
	ent "entgo.io/ent"
	entsql "entgo.io/ent/dialect/entsql"
	schema "entgo.io/ent/schema"
	field "entgo.io/ent/schema/field"
	index "entgo.io/ent/schema/index"
	uuid "github.com/google/uuid"
)

type Note struct {
	ent.Schema
}

func (Note) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).
			Unique().
			Immutable(),
		field.String("alias").
			Optional(),
		field.String("body").
			Optional(),
		field.Time("date_erased").
			Nillable().
			Optional(),
		field.Time("date_updated"),
		field.Time("date_created").
			Immutable().
			Optional(),
	}
}

func (Note) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("alias").
			Unique().
			Annotations(entsql.IndexWhere("date_erased IS NULL")),
		index.Fields("body").
			Unique(),
	}
}

func (Note) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "note"},
	}
}
