// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/seat.proto

package schema

import (
	ent "github.com/protobuf-orm/ent"
	entsql "github.com/protobuf-orm/ent/dialect/entsql"
	schema "github.com/protobuf-orm/ent/schema"
	edge "github.com/protobuf-orm/ent/schema/edge"
	field "github.com/protobuf-orm/ent/schema/field"
	index "github.com/protobuf-orm/ent/schema/index"
)

type Seat struct {
	ent.Schema
}

func (Seat) Fields() []ent.Field {
	return []ent.Field{
		field.Uuid("id").
			Unique().
			Immutable(),
		field.Uuid("holder_id"),
		field.Uuid("org_id"),
		field.Uuid("deputy_id").
			Optional(),
	}
}

func (Seat) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("holder", User.Type).
			Unique().
			Field("holder_id").
			Required(),
		edge.To("org", Tenant.Type).
			Unique().
			Field("org_id").
			Required(),
		edge.To("deputy", User.Type).
			Unique().
			Field("deputy_id"),
	}
}

func (Seat) Indexes() []ent.Index {
	return []ent.Index{
		index.Edges("holder", "org").
			Unique(),
		index.Edges("deputy").
			Unique(),
	}
}

func (Seat) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "seat"},
	}
}
