// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/shift.proto

package schema

import (
	ent "github.com/protobuf-orm/ent"
	entsql "github.com/protobuf-orm/ent/dialect/entsql"
	schema "github.com/protobuf-orm/ent/schema"
	field "github.com/protobuf-orm/ent/schema/field"
	index "github.com/protobuf-orm/ent/schema/index"
)

type Shift struct {
	ent.Schema
}

func (Shift) Fields() []ent.Field {
	return []ent.Field{
		field.Uuid("id").
			Unique().
			Immutable(),
		field.String("desk"),
		field.Time("starts_at"),
	}
}

func (Shift) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("desk", "starts_at").
			Unique(),
	}
}

func (Shift) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "shift"},
	}
}
