// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/tenant.proto

package schema

import (
	ent "entgo.io/ent"
	field "entgo.io/ent/schema/field"
	uuid "github.com/google/uuid"
)

type Tenant struct {
	ent.Schema
}

func (Tenant) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).
			Unique().
			Immutable(),
		field.String("alias").
			Optional(),
		field.String("name").
			Optional(),
		field.JSON("labels", map[string]string{}),
		field.Time("date_created").
			Immutable().
			Optional(),
	}
}
