// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/tenant.proto

package schema

import (
	ent "github.com/protobuf-orm/ent"
	entsql "github.com/protobuf-orm/ent/dialect/entsql"
	schema "github.com/protobuf-orm/ent/schema"
	field "github.com/protobuf-orm/ent/schema/field"
)

type Tenant struct {
	ent.Schema
}

func (Tenant) Fields() []ent.Field {
	return []ent.Field{
		field.Uuid("id").
			Unique().
			Immutable(),
		field.String("alias").
			Optional(),
		field.String("name").
			Optional(),
		field.Json("labels", map[string]string{}).
			Optional(),
		field.Time("date_created").
			Immutable().
			Optional(),
	}
}

func (Tenant) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "tenant"},
	}
}
