// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/user.proto

package schema

import (
	ent "entgo.io/ent"
	edge "entgo.io/ent/schema/edge"
	field "entgo.io/ent/schema/field"
	index "entgo.io/ent/schema/index"
	uuid "github.com/google/uuid"
)

type User struct {
	ent.Schema
}

func (User) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).
			Unique().
			Immutable(),
		field.String("alias").
			Optional(),
		field.String("name").
			Optional(),
		field.JSON("labels", map[string]string{}).
			Optional(),
		field.String("lock").
			Nillable().
			Optional(),
		field.Time("date_created").
			Nillable().
			Immutable().
			Optional(),
	}
}

func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("tenant", Tenant.Type).
			Unique().
			Required(),
	}
}

func (User) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("alias").
			Edges("tenant").
			Unique(),
	}
}
