// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: apptest/user.proto

package schema

import (
	ent "github.com/protobuf-orm/ent"
	entsql "github.com/protobuf-orm/ent/dialect/entsql"
	schema "github.com/protobuf-orm/ent/schema"
	edge "github.com/protobuf-orm/ent/schema/edge"
	field "github.com/protobuf-orm/ent/schema/field"
	index "github.com/protobuf-orm/ent/schema/index"
)

type User struct {
	ent.Schema
}

func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Uuid("id").
			Unique().
			Immutable(),
		field.String("alias").
			Optional(),
		field.String("name").
			Optional(),
		field.Json("labels", map[string]string{}).
			Optional(),
		field.String("lock").
			Nillable().
			Optional(),
		field.Time("date_updated"),
		field.Time("date_created").
			Immutable().
			Optional(),
		field.Uuid("tenant_id"),
	}
}

func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("tenant", Tenant.Type).
			Unique().
			Field("tenant_id").
			Required(),
	}
}

func (User) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("alias").
			Edges("tenant").
			Unique(),
	}
}

func (User) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "user"},
	}
}
