package app

import (
	"bytes"
	"fmt"
	"path/filepath"

	"github.com/protobuf-orm/protoc-gen-orm-ent/internal/work"
	"google.golang.org/protobuf/compiler/protogen"
)

// doClientWork emits, once per Ent package, the things the Ent client knows
// but will not say.
//
// It belongs here and nowhere else. Ent keeps the driver on an unexported
// field of an unexported struct, so only a file inside that package can read
// it, and this generator already writes files there. A caller outside would
// otherwise have to be told a second time what it already said when it opened
// the connection -- and a caller that repeats itself can disagree with itself.
func (a *App) doClientWork(p *protogen.Plugin, f *protogen.File) error {
	gf, ok, err := a.newGeneratedClientFile(p, f)
	if err != nil {
		return err
	}
	if !ok {
		// Already written for this package.
		return nil
	}

	xClient(gf)
	return nil
}

func (a *App) newGeneratedClientFile(p *protogen.Plugin, f *protogen.File) (*protogen.GeneratedFile, bool, error) {
	dir, _ := filepath.Split(f.GeneratedFilenamePrefix)

	// The namer names a file after an entity; this one is about the package, so
	// only the directory it chose is borrowed and the name is the option's.
	var b bytes.Buffer
	if err := a.namer.Execute(&b, struct{ Name string }{Name: "_"}); err != nil {
		return nil, false, fmt.Errorf("name %s: %w", f.GeneratedFilenamePrefix, err)
	}
	d, _ := filepath.Split(b.String())
	path := filepath.Join(dir, d, a.client)

	if gf, ok := a.gfs[path]; ok {
		return gf, false, nil
	}

	gf := p.NewGeneratedFile(path, f.GoImportPath+protogen.GoImportPath(d))
	a.gfs[path] = gf

	gf.P(`// Code generated by protoc-gen-orm-ent. DO NOT EDIT.`)
	gf.P("")
	gf.P("package ent")
	gf.P("")

	return gf, true, nil
}

// xClient writes what a server needs of the client and cannot ask for.
//
// Every one of these reads `config.driver`, which is unexported. They are four
// lines each and they are here rather than in a runtime module for that reason
// alone.
func xClient(gf *protogen.GeneratedFile) {
	ident := func(v protogen.GoIdent) string { return gf.QualifiedGoIdent(v) }

	gf.P("// Dialect is the SQL this client speaks.")
	gf.P("//")
	gf.P("// A server that writes SQL of its own has to know which SQL it may write,")
	gf.P("// and the connection is what settles that. Asking the client rather than")
	gf.P("// the caller is what keeps the answer from being a second, separate claim")
	gf.P("// that can disagree with the first.")
	gf.P("func (c *Client) Dialect() string {")
	gf.P("	return c.driver.Dialect()")
	gf.P("}")
	gf.P("")

	gf.P("// Driver is what this client runs its queries through.")
	gf.P("//")
	gf.P("// It is what a transaction is begun on when several clients are to share")
	gf.P("// one; see the enttx package and [Client.WithDriver].")
	gf.P("func (c *Client) Driver() ", ident(work.PkgEntDialect.Ident("Driver")), " {")
	gf.P("	return c.driver")
	gf.P("}")
	gf.P("")

	gf.P("// WithDriver answers with a client that runs through drv and is this one in")
	gf.P("// every other way.")
	gf.P("//")
	gf.P("// The hooks, the interceptors and the debug setting come along, which is the")
	gf.P("// point: building a fresh client from the driver reaches the same database")
	gf.P("// and quietly drops all three. This is what [Client.Tx] does to bind a")
	gf.P("// client to a transaction, spelled for a driver that came from elsewhere.")
	gf.P("func (c *Client) WithDriver(drv ", ident(work.PkgEntDialect.Ident("Driver")), ") *Client {")
	gf.P("	cfg := c.config")
	gf.P("	cfg.driver = drv")
	gf.P("	client := &Client{config: cfg}")
	gf.P("	client.init()")
	gf.P("	return client")
	gf.P("}")
	gf.P("")

	gf.P("// InTx reports whether this client is already bound to a transaction of")
	gf.P("// Ent's own, which is the one [Client.Tx] refuses to nest.")
	gf.P("//")
	gf.P("// It is the same question Tx asks itself, so a caller can ask it first")
	gf.P("// instead of starting a transaction to find out. A driver from enttx is")
	gf.P("// not one of these and does not answer true: it hands out transactions")
	gf.P("// that cannot end the one it holds, so nesting on it is already safe.")
	gf.P("func (c *Client) InTx() bool {")
	gf.P("	_, ok := c.driver.(*txDriver)")
	gf.P("	return ok")
	gf.P("}")
	gf.P("")
}
